engineered_prompt = {
    # bridge
    # "pot": "metal pot",
    # "can": "metal can",
    # "pan": "metal pan",
    "eggplant": "purple eggplant",
    # iamlab_cmu_pickup_insert_converted_externally_to_rlds
    "pink flower": "pink block",
    # taco_play
    "square bread": "toast",
    "milk dairy": "milk carton",
    # fractal, follows https://arxiv.org/abs/2303.00905
    "7up can": "white can of soda",
    "banana": "banana",
    "black pen": "black pen",
    "blue chip bag": "blue bag of chips",
    "blue pen": "blue pen",
    "brown chip bag": "brown bag of chips",
    "cereal scoop": "cereal scoop",
    "chocolate peanut candy": "bag of candy snack",
    "coffee cup": "coffee cup",
    "coke can": "red can of soda",
    "coke zero can": "can of soda",
    "disinfectant pump": "bottle",
    "fork": "fork",
    "green can": "green aluminum can",
    "green cookies bag": "green snack food bag",
    "green jalapeno chip bag": "green bag of chips",
    "green sprite can": "green soda can",
    "knife": "knife",
    "orange can": "orange aluminum can",
    "orange plastic bottle": "orange bottle",
    "oreo": "cookie snack food bag",
    "pepsi can": "blue soda can",
    "popcorn chip bag": "bag of chips",
    "pretzel chip bag": "bag of chips",
    "red grapefruit can": "red aluminum can",
    "redbull can": "skinny silver can of soda",
    "rxbar blueberry": "chocolate bar", # modified
    "spoon": "spoon",
    "swedish fish bag": "bag of candy snack food",
    "water bottle": "clear plastic waterbottle with white cap",
    "white sparkling can": "aluminum can",
    "blue plastic bottle": "clear plastic waterbottle with white cap",
    "diet pepper can": "can of soda",
    "disinfectant wipes": "yellow and blue pack",
    "green rice chip bag": "green bag of chips",
    "orange": "round orange fruit",
    "paper bowl": "round bowl",
    "rxbar chocolate": "chocolate bar", # modified
    "sponge": "scrub sponge",
    "blackberry hint water": "clear plastic bottle with white cap",
    "pineapple hint water": "clear plastic bottle with white cap",
    "watermelon hint water": "clear plastic bottle with white cap",
    "regular 7up can": "can of soda",
    "lemonade plastic bottle": "clear plastic bottle with white cap",
    "diet coke can": "silver can of soda",
    "yellow pear": "yellow pear",
    "green pear": "green pear",
    "instant oatmeal pack": "flat brown pack of instant oatmeal",
    "coffee mixing stick": "small thin flat wooden popsicle stick",
    "coffee cup lid": "round disposable coffee cup lid",
    "coffee cup sleeve": "brown disposable coffee cup sleeve",
    "numi tea bag": "small flat packet of tea",
    "fruit gummies": "small blue bag of snacks",
    "chocolate caramel candy": "small navy bag of candy",
    "original redbull can": "can of energy drink with dark blue label",
    "cold brew can": "blue and black can",
    "ginger lemon kombucha": "yellow and tan aluminum can with brown writing",
    "large orange plate": "circular orange plate",
    "small blue plate": "circular blue plate",
    "love kombucha": "white and orange can of soda",
    "original pepper can": "dark red can of soda",
    "ito en green tea": "light green can of soda",
    "iced tea can": "black can of soda",
    "cheese stick": "yellow cheese stick in wrapper",
    "brie cheese cup": "small white cheese cup with wrapper",
    "pineapple spindrift can": "white and cyan can of soda",
    "lemon spindrift can": "white and brown can of soda",
    "lemon sparkling water can": "yellow can of soda",
    "milano dark chocolate": "white pack of snacks",
    "square cheese": "small orange rectangle packet",
    "boiled egg": "small white egg in a plastic wrapper",
    "pickle snack": "small black and green snack bag",
    "red cup": "plastic red cup",
    "blue cup": "plastic blue cup",
    "orange cup": "plastic orange cup",
    "green cup": "plastic green cup",
    "head massager": "metal head massager with many wires",
    "chew toy": "blue and yellow toy with orange polka dots",
    "wrist watch": "wrist watch",
    "small orange rolling pin": "small orange rolling pin with wooden handles",
    "large green rolling pin": "large green rolling pin with wooden handles",
    "rubiks cube": "rubiks cube",
    "blue microfiber cloth": "blue cloth",
    "gray microfiber cloth": "gray cloth",
    "green microfiber cloth": "green cloth",
    "small blending bottle": "small turquoise and brown bottle",
    "large tennis ball": "large tennis ball",
    "table tennis paddle": "table tennis paddle",
    "octopus toy": "purple toy octopus",
    "pink shoe": "pink shoe",
    "floral shoe": "red and blue shoe",
    "whisk": "whisk",
    "orange spatula": "orange spatula",
    "small blue spatula": "small blue spatula",
    "large yellow spatula": "large yellow spatula",
    "egg separator": "large pink cooking spoon",
    "green brush": "green brush",
    "small purple spatula": "small purple spatula",
    "badminton shuttlecock": "shuttlecock",
    "black sunglasses": "black sunglasses",
    "toy ball with holes": "toy ball with holes",
    "red plastic shovel": "red plastic shovel",
    "bird ornament": "colorful ornament with blue and yellow confetti",
    "blue balloon": "blue balloon animal",
    "catnip toy": "small dark blue plastic cross toy",
    "raspberry baby teether": "red and green baby pacifier",
    "slinky toy": "gray metallic cylinder slinky",
    "dna chew toy": "big orange spring",
    "gray suction toy": "gray suction toy",
    "teal and pink toy car": "teal and pink toy car",
    "two pound purple dumbbell": "purple dumbbell",
    "one pound pink dumbbell": "pink dumbbell",
    "three pound brown dumbbell": "brown dumbbell",
    "dog rope toy": "white pink and gray rope with knot",
    "fish toy": "fish",
    "chain link toy": "skinny green rectangular toy",
    "toy boat train": "plastic toy boat",
    "white coat hanger": "white coat hanger"
}